const spanish = {
  'user-about-me': 'Sobre mi',
  'user-profile': 'Desarrollador fullstack',
  'user-information': 'Hola soy un desarrollador que le gusta programar en sus tiempos libres, con experiencia en el mundo de la informática.',
  'user-education': 'Educación',
  'user-university-title': 'Universidad',
  'user-university-1': 'Ingenieria en computación',
  'user-high-school-title': 'Bachillerato',
  'user-high-school-title-1': 'Técnico en soporte y mantenimiento de equipo de cómputo',
  'user-secondar-title': 'Secundaria',
  'user-experience-title': 'Experiencia',
  'user-technologies-title': 'Tecnologias',
  'user-hobbies-title': 'Pasatiempos',
  'user-setting-title': 'Configuración',
  'user-language-title': 'Idioma',
  'user-menu-close': 'Cerrar',
  'user-technologies-more-information': 'Ver',
  'user-company-indra-title': 'Indra Sistemas México',
  'user-company-indra-position': 'Consultor',
  'user-company-indra-activity-1': 'Apoyo en entrevistas para nuevos integrantes',
  'user-company-indra-activity-2': 'Asignación en el proyecto de GLOMO-MX',
  'user-company-bbva-title': 'BBVA México',
  'user-company-bbva-position': 'Lider de incidencias',
  'user-company-bbva-activity-1': 'Gestión en el area de servicios del canal.',
  'user-company-bbva-activity-2': 'Llevar a cabo la bitacora de las liberaciones de la aplicación y presentación de los servicios alertados.',
  'user-company-bbva-activity-3': 'Solución de bugs en la aplicación',
  'user-company-bbva-activity-4': 'Apoyo de incidencias productivas',
  'user-company-bbva-activity-5': 'Revisión del codigo en los repositorios aplicando buenas prácticas',
  'user-company-bbva-activity-6': 'Refactorización y atención del codigo, tanto en pruebas unitarias como a nivel aplicativo',
  'user-company-bbva-activity-7': 'Soporte en la construcción de los jobs en los repositorios',
  'user-project-movie-app': 'Web realizada con javascript, css y html puro en la cual se realiza el consumo de un API de peliculas y muestra el detalle de cada una de ellas',
  'user-project-dragon-ball-app': 'Primera aplicación realizada con Vue en la cual se utiliza el Api de dragon ball',
  'user-projects-title': 'Proyectos'
};

const english = {
  'user-about-me': 'About me',
  'user-profile': 'Fullstack developer',
  'user-information': 'Hello, I am a developer who likes to program in his free time, with experience in the world of computing.',
  'user-education': 'Education',
  'user-university-title': 'University',
  'user-university-1': 'Computer engineering',
  'user-high-school-title': 'High school',
  'user-high-school-title-1': 'Technician in support and maintenance of computer equipment',
  'user-secondar-title': 'Secondary',
  'user-experience-title': 'Experience',
  'user-technologies-title': 'Technologies',
  'user-hobbies-title': 'Hobbies',
  'user-setting-title': 'Setting',
  'user-language-title': 'Language',
  'user-menu-close': 'Close',
  'user-technologies-more-information': 'See',
  'user-company-indra-title': 'Indra Systems Mexico',
  'user-company-indra-position': 'Consultant',
  'user-company-indra-activity-1': 'Support in interviews for new members.',
  'user-company-indra-activity-2': 'Assignment in the GLOMO-MX project.',
  'user-company-bbva-title': 'BBVA Mexico',
  'user-company-bbva-position': 'Incident leader',
  'user-company-bbva-activity-1': 'Management in the channel services area.',
  'user-company-bbva-activity-2': 'Carry out the log of application releases and presentation of the alerted services.',
  'user-company-bbva-activity-3': 'Bug fixes in the application.',
  'user-company-bbva-activity-4': 'Support of productive incidents.',
  'user-company-bbva-activity-5': 'Review of the code in the repositories applying good practices',
  'user-company-bbva-activity-6': 'Refactoring and attention to the code, both in unit tests and at the application level.',
  'user-company-bbva-activity-7': 'Support in the construction of jobs in the repositories.',
  'user-project-movie-app': 'Web made with JavaScript, CSS and HTML Pure in which the consumption of a movie API is made and shows the detail of each of them',
  'user-project-dragon-ball-app': 'First application made with Vue in which the Dragon Ball API is used',
  'user-projects-title': 'Projects'
}

export { spanish, english };